### PR TITLE
Update to MC 1.15.2

### PR DESCRIPTION
**Pull request by Lupus590**
Making this early because I'm expecting to need help on it at some point

### CODE REVIEW

**Comment by Lupus590** [comment]
closes https://github.com/SquidDev-CC/plethora/issues/237

**Comment by fionera** [comment]
Will you continue this?

**Comment by Lupus590** [comment]
I plan to, but I'm in a bit of a limbo of not knowing enough to continue and not having the motivation to learn how to continue.

If anyone wants to help then they can contribute to my fork and we can make this pull request together. Or just fork my fork and carry on without me.

**Comment by fionera** [comment]
I took your commits and after a rebase onto the current master I started fixing errors :) https://github.com/fionera/plethora/commit/16d81a9787f38f48ed29e0eeb5f378745bc1c6e1

**Comment by Lupus590** [comment]
1.15.2 seems to be the new popular version for modding so I'm going to target that instead, starting with what @fionera 's fork has. Hopefully, I keep at it a bit longer, or we could just hot potato back and forth.

**Comment by Lupus590** [comment]
closing as I want to have my branch name match, I'll make a new pull request if I get stuff moving reasonably.

**Pull request closed without merging**
