### PR TITLE
[WIP] Terminal glasses implementation

### LINKED ISSUE #39: Terminal glasses
It would be really nice to have some form of OpenPeirpheral's terminal glasses. Obviously these will be integrated directly into the neural interface rather than using a terminal bridge. It might be worth looking at [OpenGlasses](http://minecraft.bymarcin.com/OpenGlasses/doku.php?id=start) functions to get an idea of some of the functionality we could add.

---

## Core functionality
 - [x] 2D objects (rectangle, dot, line, triangle, line strip, polygon, text)
   - [ ] Z-index control
 - [x] Object groups. Perhaps we could store the parent ID in each object, and inherit properties from there? We'd need to think about how this interacts with z-indexes.
 - [x] 3D objects (rectangle, dot, line, triangle, cube, polygon, text) It would be good if rectangles, lines and text came in "floating" (facing you) and "normal" varieties.
 - [ ] Render 2D canvas on manipulator.
 - [ ] Optimise network packets: compute diff of changes, compress, etc...

## Other things
 - [x] Block/Fluid/Item rendering
 - [ ] Particles

### PR DESCRIPTION
**Pull request by SquidDev**
- [x] Add items
 - [x] Add 2D objects (rectangle, dot, line, triangle, line strip, polygon, text)
 - [ ] Add 3D objects (rectangle, dot, line, triangle, cube, polygon, text) It would be good if rectangles, lines and text came in "floating" (facing you) and "normal" varieties.
 - [ ] Somehow render 2D canvas on manipulator.
 - [ ] Optimise network packets: compute diff of changes, compress, etc...

## Other things
 - [ ] Block/Fluid/Item rendering
 - [ ] Particles

Closes #39

### CODE REVIEW

**Comment by SquidDev** [comment]
It's a start:

**Comment by SquidDev** [comment]
As per @Lemmmy's comments: it would be nice if we could have a way to render fluid/block tiles and items. I can imagine the former being especially useful in a 3D view.

**Comment by Lemmmy** [comment]
fluids and such can also be useful for your typical bigreactor HUDs - use different fluids for fuel progress bars etc

items can be useful for a remote AE, and also for other statistics

**Comment by Lignum** [comment]
I have some concerns about your OpenGL :stuck_out_tongue:.

You're rendering objects directly with immediate mode (`glBegin`/`glEnd`), which is _really_ not a good idea. Minecraft expects you to use `Tessellator` so that it can do all the optimisations it needs to do, but that might be a little awkward to do here.

The best solution, I think, would be to track changes to the canvas and update a display list every time it does so. That means you get to keep your current `glBegin`/`glEnd` code, but you're essentially "recording" those commands into a buffer so that they can be batch executed with `glCallList`, which is not very modern or ideal, but that's already higher than Minecraft's standards, and it should give you a pretty decent speedup.

Additionally, you make some direct calls to state-mutating functions like `GL11.glTranslatef` and `GL11.glColor3f`, which `GlStateManager` has functions for (`GlStateManager.translate`, `GlStateManager.color`), but I'm not sure if they're available in 1.8.

**Comment by SquidDev** [comment]
> I have some concerns about your OpenGL 😛.

Yeah, me too.

> Minecraft expects you to use `Tessellator` so that it can do all the optimisations it needs to do, but that might be a little awkward to do here.

Do you know if it would be any performance changes here? I'm using different draw modes for every object, so I don't know if there is any possible gain.

> The best solution, I think, would be to track changes to the canvas and update a display list every time it does so. 

OK. I will look into this. Do you think you could PR some changes into this branch/walk me through it?

> Additionally, you make some direct calls to state-mutating functions like `GL11.glTranslatef` and `GL11.glColor3f`, which `GlStateManager` has functions for.

Yeah. I ended up having to use `GL11.glEnable`/`Gl11.glDisable` instead of the `GLStateManager` versions as I was using `pushAttrib`/`popAttrib`, which doesn't play super well with the state manager. I could still use the `GLStateManager` functions for transformations though.

Thanks for the feedback!

**Comment by Lignum** [comment]
@SquidDev 

> Do you know if it would be any performance changes here? I'm using different draw modes for every object, so I don't know if there is any possible gain.

Yes, Minecraft would use VBOs if they are enabled, which is the optimal way to render graphics. You would only get the full performance out of using the `Tessellator` if you stick to a single mode. Since all shapes that don't have perfect curves can be made up of triangles, you might as well just convert your code to triangles. This is also beneficial since `glPointSize` has an undefined limit (but it's usually around `32.0f`).

> OK. I will look into this. Do you think you could PR some changes into this branch/walk me through it?

Sure, I can provide you with some pseudocode.
```Java
private int displayList = -1;

public void init() {
  // Doesn't matter where this is called, probably in your canvas constructor.
  // Definitely has to be after there's an OpenGL context, but that should usually be the case.
  displayList = glGenLists();
  glNewList(displayList, GL_COMPILE);
  // Anything between this is recorded into the display list. Initially, we want it to be empty.
  glEndList();
}

public void renderCanvas() {
  if (canvasChanged) {
    // If the canvas has changed, we'll record a new display list.
    // Since we're not doing glGenLists here, OpenGL knows that you
    // want it updated, not re-created.
    glNewList(displayList, GL_COMPILE);

    // You can put most OpenGL code in here and it will be recorded,
    // meaning draw2D/draw3D stays the same.
    for (obj in objects)
      obj.draw2D();

    glEndList();
    canvasChanged = false;
  }

  // This draws all canvas elements in one go.
  glCallList(displayList);
}

public void uninit() {
  // Called when the canvas is never used again.
  glDeleteLists(1, displayList);
}
```

**Comment by dunstad** [comment]
The terminal glasses from OpenPeripherals have a function addIcon which allows you to display the icon of an item as it would appear in your inventory on the screen. Any chance that could be implemented here?

**Comment by SquidDev** [comment]
I've pulled some of this into master. 3D stuff will appear in a later release.

**Pull request closed without merging**
